import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Topbar } from "@/components/Topbar";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "URL Shortener - MinLink",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex flex-col min-h-screen bg-indigo-950 mx-auto px-4">
        <Topbar />
        <main className="flex flex-col justify-center max-h-[90vh] gap-3 w-full">
          {children}
        </main>
        <Footer />
        <Toaster/>
      </body>
    </html>
  );
}
